# Read the Docs configuration file for gh-oauth-helper
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and requirements required to build the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install uv for faster dependency management
      - python -m pip install uv
      # Install our project with all documentation dependencies using uv
      - uv pip install -e ".[docs]" --system

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build the docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Dependencies are handled by uv in the post_create_environment job above

